# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7a1653538a8606124dcfe5a600ace3eee71fc494566f10a1286c453592af17d49369c5daec1df040269dfc08aa0201c44f6ead15ba681a6e25ba8655f6cfb31

test:
  secret_key_base: 872e106bc0ea4b200f037bc5de3dc9574eda0adc98d48a5dfad7a3d94004c0775880ab0861288e0498508582dc7fb8ada4c7bf29fd6b629e761ac06baa939664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
